### ISSUE TITLE
Have you developed a smell ontology?

### ISSUE THREAD

**Issue by Addaci** [Smelly-London/Smelly-London#4]
Have you developed a smell ontology or are you using an existing ontology? If so, could you share it with the Maphackathon GitHub organisation? Many thanks, Colin Greenstreet (@addaci)

**Comment by Violin1208** [comment]
Hi Colin

Yes, I do have one although the it need further development. I'll be happy
to share it this weekend.

Thank you.
Deborah

**Comment by Addaci** [comment]
Hi Deborah,

That's great. I'm really looking forward to working with you - gentle
reminder though that you still need to get your ticket:
https://www.eventbrite.co.uk/e/maphackathon-tickets-30469473014

We have announced the full weekend schedule this morning:
https://www.meetup.com/meetup-group-SwyKxWXR/pages/22292845/Schedule_for_weekend_Maphackathon%2C_Feb_11-12%2C_2017

We have also provided details of the chairman of the judging panel and the
top prize:
https://www.meetup.com/meetup-group-SwyKxWXR/pages/22293041/Entrepreneur_Steve_Ives%2C_chairman_of_judging_panel

Klokan Technology will be doing its world launch of its exciting new
product GeoEditor for MapTiler at our event and doing the European launch
of its product Georeferencer ver 4:
https://www.meetup.com/meetup-group-SwyKxWXR/pages/22266928/Exciting_news_-_product_launch_at_Maphackathon/

Details of the two Saturday afternoon workshops are here

Workshop 1: hands on QGIS & ArcGIS training:
https://www.meetup.com/meetup-group-SwyKxWXR/pages/22255958/5_ArcGIS_in_Cloud_accounts_free_for_two_day_hack/
Workshop 2: Handson georeferencing training:
https://www.meetup.com/meetup-group-SwyKxWXR/pages/22288809/Saturday_PM_hands_on_georeferencing_workshop/

Our Maphackathon data repository is growing fast, with lots more data to
come tonight and tomorrow: https://github.com/Maphackathon/data-sets [You
need a GitHub IS to view; if you do not yet have a GitHub ID, please join
and email details to colin.greenstreet@gmail.com, who will join you to the
Maphackathon GitHub organisation

Best wishes

Colin Greenstreet

Co-director, MarineLives; co-producer, Early Modern Thames Maphackathon


E:colin.greenstreet@gmail.com

W: http://www.maphackathon.org; http://www.marinelives.org


Twitter: @maphackathon #maphackathon @marinelivesorg

T: +44-20-8883-0135

M: +44-(0)7769-340229

Skype: colingreenstreet.marinelives
